#!/bin/sh

# This script is run before the package files are transferred to @appstore.
# You can check if the installation requirements meet the DSM or package version, or if some services are enabled in this script. 


exit 0
